services:
  model:
    build:
      context: ./model
    expose:
      - "8080"
    volumes:
      - ./model:/app
      - /app/.venv # do not clobber installed venv
      - ~/.aws/:/root/.aws:ro
    healthcheck:
      test: curl --fail 'http://localhost:8080/healthcheck' || exit 1
      start_period: 60s
      interval: 5s
      retries: 12
    depends_on:
      qdrant:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - caddy-net
    env_file: .env

  frontend:
    build:
      context: ./frontend
    expose:
      - "4322"
    entrypoint: npm run dev
    env_file: .env
    networks:
      - caddy-net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: curl --fail 'http://localhost:4322/' || exit 1
      start_period: 60s
      interval: 5s
      retries: 12
    depends_on:
      model:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant:v1.15.5
    ports:
      - '6333:6333'
      - '6334:6334'
    expose:
      - 6333
      - 6334
      - 6335
    env_file: .env
    restart: always
    volumes:
      - qdrant_storage:/qdrant/storage:z
    networks:
      - caddy-net
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/localhost/6333' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    image: pgvector/pgvector:pg18
    ports:
      - '5432:5432'
    environment:
    - POSTGRES_USER=root # because root will execute the init script
    - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./model/scripts/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      retries: 12
      start_period: 60s
      interval: 5s
    networks:
      - caddy-net

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server --console-address ":9001" /data
    networks:
      - caddy-net
    volumes:
      - minio_data:/var/lib/minio/data:Z
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      retries: 12
      start_period: 60s
      interval: 5s

  client:
    image: public.ecr.aws/idotai/gov-ai-client:0891f9633f143f967a3382720be9dbfcb3d8c1d8
    container_name: gov-ai-client
    expose:
      - "8081"
    env_file: .env
    networks:
      - caddy-net

volumes:
  postgres_data:
  qdrant_storage:
  minio_data:

networks:
  caddy-net:
