services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"    # model
      - "8081:81"    # client
      - "8082:82"    # frontend
    volumes:
      - ./docker-compose-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-compose-config/user-switcher.conf:/etc/nginx/user-switcher.conf:ro
    depends_on:
      - model
      - frontend
      - client
    networks:
      - caddy-net
    restart: unless-stopped

  model:
    build:
      context: ./model
    expose:
      - "8080"
    volumes:
      - ./model:/app
      - /app/.venv # do not clobber installed venv
      - ~/.aws/:/root/.aws:ro
    healthcheck:
      test: curl --fail 'http://localhost:8080/healthcheck' || exit 1
      start_period: 60s
      start_interval: 1s
      retries: 10
    depends_on:
      opensearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - caddy-net
    env_file: "docker-compose-config/.env"

  frontend:
    build:
      context: ./frontend
    expose:
      - "4322"
    entrypoint: npm run dev
    env_file: "docker-compose-config/.env"
    networks:
      - caddy-net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: curl --fail 'http://localhost:4322/' || exit 1
      start_period: 60s
      start_interval: 1s
      retries: 10
    depends_on:
      model:
        condition: service_healthy

  opensearch:
    build:
      dockerfile: docker-compose-config/opensearch.Dockerfile
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - logger.level=ERROR
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    # ulimit values come from the opensearch Docker docs
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      # we're happy to be yellow because green indicates replicas are up... and we don't have replicas!
      test: curl --fail http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 60s
      start_interval: 1s
    restart: unless-stopped
    networks:
      - caddy-net

  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - '5432:5432'
    environment:
    - POSTGRES_USER=root # because root will execute the init script
    - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./model/scripts/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      retries: 10
      start_period: 60s
      start_interval: 1s
    networks:
      - caddy-net

  minio:
    image: minio/minio
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server --console-address ":9001" /data
    networks:
      - caddy-net
    volumes:
      - minio_data:/var/lib/minio/data:Z
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      retries: 20
      start_period: 60s
      start_interval: 1s

  client:
    image: public.ecr.aws/idotai/gov-ai-client:068ee7adce7c62c6836239c57415d517cf870dd5
    container_name: gov-ai-client
    expose:
      - "8081"
    env_file: "docker-compose-config/.env"
    networks:
      - caddy-net

  welcome:
    restart: no
    build:
      context: docker-compose-config
      dockerfile: welcome.Dockerfile
    depends_on:
      frontend:
        condition: service_healthy

  dex:
    image: dexidp/dex:v2.39.1
    ports:
      - "5556:5556"
    volumes:
      - ./docker-compose-config/dex-config.yaml:/etc/dex/config.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    networks:
      - caddy-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5556/dex/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  opensearch_data:
  postgres_data:
  minio_data:

networks:
  caddy-net: