"""Added custom prompt to collection table

Revision ID: 340fc40a6965
Revises: 67029bed5083
Create Date: 2025-09-08 14:12:06.857992

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "340fc40a6965"  # pragma: allowlist secret
down_revision: Union[str, None] = "67029bed5083"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column(
            "custom_prompt",
            sqlmodel.sql.sqltypes.AutoString(length=5096),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "custom_prompt")
    # ### end Alembic commands ###
