"""Collection name length

Revision ID: 37c15fe1ab58
Revises: f7bb12c62f44
Create Date: 2025-07-10 14:43:57.189097

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37c15fe1ab58"  # pragma: allowlist secret
down_revision: Union[str, None] = "f7bb12c62f44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sqlmodel.sql.sqltypes.AutoString(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=36),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
