"""empty message

Revision ID: 46dd2326fb04
Revises: da4b892c3a0b
Create Date: 2025-06-13 16:39:50.921560

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46dd2326fb04"
down_revision: Union[str, None] = "da4b892c3a0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resource", sa.Column("created_by_id", sa.Uuid(), nullable=True))
    op.drop_constraint("resource_created_by_fkey", "resource", type_="foreignkey")
    op.create_foreign_key(
        None, "resource", "user", ["created_by_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("resource", "created_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource",
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "resource", type_="foreignkey")
    op.create_foreign_key(
        "resource_created_by_fkey", "resource", "user", ["created_by"], ["id"]
    )
    op.drop_column("resource", "created_by_id")
    # ### end Alembic commands ###
