"""Convert uppercase emails to lowercase

Revision ID: 67029bed5083
Revises: 37c15fe1ab58
Create Date: 2025-09-08 12:38:44.651841

"""

from typing import Sequence, Union

from sqlalchemy.orm import Session

from alembic import op
from api.data_structures.models import User
from api.environments.environment import config

# revision identifiers, used by Alembic.
revision: str = "67029bed5083"  # pragma: allowlist secret
down_revision: Union[str, None] = "37c15fe1ab58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


logger = config.get_logger(__name__)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if config.env.lower() != "test":
        connection = op.get_bind()
        session = Session(connection)
        try:
            users = session.query(User).all()

            for user in users:
                user.email = user.email.lower()
                session.add(user)
                session.commit()
                session.refresh(user)
        except Exception:
            logger.exception(
                "Error converting user email to lowercase",
            )
            session.rollback()
            raise
        finally:
            session.close()

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
