"""Convert uppercase emails to lowercase

Revision ID: 67029bed5083
Revises: 37c15fe1ab58
Create Date: 2025-09-08 12:38:44.651841

"""

from typing import Sequence, Union

from sqlalchemy import select
from sqlmodel import Session

from api.environment import config
from api.models import User

# revision identifiers, used by Alembic.
revision: str = "67029bed5083"  # pragma: allowlist secret
down_revision: Union[str, None] = "37c15fe1ab58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(config.get_database()) as session:
        stmt = select(User)

        users = session.scalars(stmt)

        for user in users:
            user.email = user.email.lower()
            session.add(user)
            session.commit()
            session.refresh(user)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
