"""added CASCADE relationships

Revision ID: da4b892c3a0b
Revises: 65850da1c60f
Create Date: 2025-05-29 14:37:49.280161

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da4b892c3a0b"  # pragma: allowlist secret
down_revision: Union[str, None] = "65850da1c60f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("resource_collection_id_fkey"), "resource", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "resource", "collection", ["collection_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("usercollection_user_id_fkey"), "usercollection", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("usercollection_collection_id_fkey"), "usercollection", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "usercollection",
        "collection",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "usercollection", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usercollection", type_="foreignkey")
    op.drop_constraint(None, "usercollection", type_="foreignkey")
    op.create_foreign_key(
        op.f("usercollection_collection_id_fkey"),
        "usercollection",
        "collection",
        ["collection_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("usercollection_user_id_fkey"),
        "usercollection",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "resource", type_="foreignkey")
    op.create_foreign_key(
        op.f("resource_collection_id_fkey"),
        "resource",
        "collection",
        ["collection_id"],
        ["id"],
    )
    # ### end Alembic commands ###
