"""Added URL to resource

Revision ID: f7bb12c62f44
Revises: 357bfc5f40d2
Create Date: 2025-07-04 16:17:02.127148

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7bb12c62f44"
down_revision: Union[str, None] = "357bfc5f40d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource", sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource", "url")
    # ### end Alembic commands ###
