name: build caddy scraper

on:
  push:
    branches:
      - main
    paths:
      - scraper/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./scraper
          push: false
          tags: caddy-scraper:${{ github.sha }}
